# DEVELOPMENT CONFIGURATION - Change credentials for production
appname = Casdoor-OAuth2-Server
httpport = 8000
driver = postgres
dataSource = postgres://casdoor:CHANGE_ME_PASSWORD@casdoor_postgres:5432/casdoor?sslmode=disable
dbName = casdoor
